version: "3.9"
services:
    simple-api.dev:
        image: infraunnes/php:8.3-apache-rdkafka
        environment:
            CREATE_LARAVEL_STORAGE: "1"
            COMPOSERMIRROR: "https://mirrors.cloud.tencent.com/composer/"
            NPMMIRROR: "https://registry.npmmirror.com"
        ports:
            - "8024:80"
        volumes:
            - "../tglindo:/var/www"
            - "../tglindo/apache-default.conf:/etc/apache2/sites-available/000-default.conf:ro"
        working_dir: /var/www

volumes:
    my-datavolume:
        external: true